version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/srv:rw

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - db:/var/lib/mysql:rw

  nginx:
    build: docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/srv:ro
      - cache:/var/cache/nginx:rw

volumes:
  db:
  cache:
