version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - storage:/srv/storage:rw
      - files:/srv/web/files:rw

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - db:/var/lib/mysql:rw

  nginx:
    build: docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - files:/srv/web/files:ro
      - cache:/var/cache/nginx:rw
      - certs:/etc/letsencrypt/live:rw
      - wellknown:/acme:ro

  certbot:
    build: docker/certbot
    volumes:
      - certs:/etc/letsencrypt/live:rw
      - wellknown:/acme:rw
      - letsencrypt:/var/lib/letsencrypt:rw

volumes:
  # php
  storage:
  files:

  # mariadb
  db:

  # nginx
  cache:

  # certbot
  certs:
  wellknown:
  letsencrypt:
