fieldLayouts:
  3ba54560-4c18-45ce-87d8-c72d31250207:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 7d6a6de4-512d-4d26-b676-b42281820960 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 75ac44a7-7b29-4f60-9a4b-b33ae969d659 # Sections
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: home
hasTitleField: false
name: Home
section: b162c2bc-a2d5-457c-bb74-6f1eefeef283 # Home
sortOrder: 1
titleFormat: '{entry.headline ?: section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
