dateModified: 1636785179
email:
  fromEmail: me@gwilyn.com
  fromName: 'Field Assistant'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    4d65c3e1-74e7-4928-87b3-d5a02c0f1f31: Home # Home
    7d6a6de4-512d-4d26-b676-b42281820960: Headline # Headline
    75ac44a7-7b29-4f60-9a4b-b33ae969d659: Sections # Sections
    477ba8bd-7405-463f-952f-01d908f23f98: 'Field Assistant' # Field Assistant
    5093d368-21f7-490b-b8a2-0ac99353bfae: Common # Common
    67642075-3d1e-4031-94ce-cd8c6c18619a: Pages # Pages
    b162c2bc-a2d5-457c-bb74-6f1eefeef283: Home # Home
    c63808e4-5bf8-447c-9df6-b6079263b538: Title # Title
    d061d272-6670-473c-a61d-8701b118cbee: Richtext # Richtext
    e21b82e3-7f96-484b-8415-d8443fd3b775: 'Field Assistant' # Field Assistant
    eef96585-3b3f-4075-a7d9-14b8fd529beb: Default # Default
    f4d54d78-7f9f-493a-9bcf-8ba4d4fbf264: Content # Content
    fe6e9762-9e4c-4df2-963a-69ba588a6106: 'block Content' # block Content
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: 'Field Assistant'
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
